### ISSUE TITLE
Add support for namespaces

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/cmd-admission-webhook-k8s#126]
## Description

Since NSM is able to provide vl3 networks, it could be useful to add support for labled namespaces. All pods within the labled namespace could be handled by the webhook that injects nsm client based on the NSM label.

**Comment by denis-tingaikin** [comment]
@edwarnicke I think this could be an inresting one for v1.5.0

**Comment by edwarnicke** [comment]
@denis-tingaikin Could you say more? :)

**Comment by denis-tingaikin** [comment]
@edwarnicke Sure.

## Use-case

1. The k8s admin deploys a namespace:
```
kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    "networkservicemesh.io": "kernel://my-vl3-network/my-iface"
```
2. k8s admin deploy a pod into that namespace (note the pod doesnt have nsm annotation)
3. the pod  is handled by the admission webhook
4.  the pod got vl3 network from NSM via injected NSC

Makes sense?
